# yamllint configuration
# https://yamllint.readthedocs.io/

extends: default

rules:
  # Line length - relaxed for Kubernetes manifests
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: disable  # Disable comment indentation check

  # Truthy values - allow 'yes', 'no', 'on', 'off' commonly used in Ansible
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Braces and brackets
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Document markers
  document-start: disable
  document-end: disable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Key duplicates
  key-duplicates: enable

  # New line at end of file
  new-line-at-end-of-file: enable

  # Trailing spaces
  trailing-spaces: enable

ignore: |
  node_modules/
  .git/
  .venv/
  dist/
  # Helm templates use Go templating which isn't valid YAML
  runtime/jupyterhub/templates/
  # Generated files
  *.generated.yaml
