# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

packages:
  - "packages/*"
  - "apps/*"

catalog:
  # Linting
  eslint: ^9.28.0
  "@eslint/js": ^9.28.0
  typescript-eslint: ^8.33.1
  globals: ^16.2.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20

  # TypeScript
  typescript: ^5.9.3
  "@types/node": ^25.2.3
  "@types/react": ^19.2.13
  "@types/react-dom": ^19.2.3

  # React
  react: ^19.2.4
  react-dom: ^19.2.4

  # Build tools
  vite: ^7.3.1
  "@vitejs/plugin-react": ^5.1.4
